// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

// Response defines model for response.
type Response struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// N200 defines model for 200.
type N200 = Response

// N302 defines model for 302.
type N302 = Response

// N400 defines model for 400.
type N400 = Response

// N404 defines model for 404.
type N404 = Response

// N500 defines model for 500.
type N500 = Response
