name: Run Make File
'on': pull_request
jobs:
  build-spec-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Make File
        run: make setup && make gen
      - name: Commit Generated Files
        run: git add . && git commit -m "Add generated files" && git push