name: Run Make File
on: pull_request

jobs:
  build-spec-file:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: npm install
        run: |
          npm install -g swagger-cli
          npx swagger-cli bundle -o OpenAPI.yml -t yaml src/root.yml
      - name: run openapi2go.sh
        run: sh oapi2go.sh
      - name: run openapi2typescript.sh
        run: sh oapi2ts.sh
      - name: commit push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Commit message"
          git push